# Generated by Django 5.0.4 on 2024-05-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurerequest',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
